### ISSUE TITLE
Does not works inside vue-bootstrap dropdown

### ISSUE THREAD

**Issue by tokomeno** [xwpongithub/vue-range-slider#16]
Here are example works outside dropdown but not in the inside

https://jsfiddle.net/o872hbzd/

**Comment by zihniogmen** [comment]
Because without clicking the dropdown toggle button, container of the menu items has zero width and height. And this component resizes automatically relative to its parent.

You could listen to "show" event (https://bootstrap-vue.org/docs/components/dropdown#listening-to-dropdown-changes-via-root-events ) of b-dropdown and then refresh the vue-range-slider component.

Example : https://jsfiddle.net/0r73qj48/
